spring:
  application:
    name: demo
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update  # Automatically create tables
    show-sql: true     # Show SQL queries in the logspring:
    defer-datasource-initialization: true
  output:
    ansi:
      enabled: always
  sql:
    init:
      mode: embedded
